const std = @import("std");
const res = @import("lenore-resources");
const text = @import("lenore-text");

const testing = std.testing;

// The second test asset, and the one that has shaping features at all.
//
// Ahem answers everything about metrics and rasterisation and nothing about
// shaping: it carries no `GSUB`, `GPOS` or `kern` table, so a ligature, a
// contextual form and a kern pair are all unreachable through it. It also
// cannot answer whether a rasterisation mode moves the shaper's advances,
// because every Ahem advance is a whole em and would survive a rounding to
// whole pixels unchanged.
//
// This one is generated by `tools/make_feature_font.py`, so every number below
// is exact by construction rather than measured off someone else's design. The
// em is 1024 units, which makes one pixel exactly 64 units at this size and one
// unit exactly one step of the 26.6 grid HarfBuzz reports on: an advance here
// is exact in f32 and compared with `==`.
const feature = @embedFile("fonts/Feature.ttf");
const pixel_size = 16;

// The generator's own numbers, in pixels at `pixel_size`. The face is
// proportional, which is the whole point: two glyphs of different advances are
// what makes a rounding to whole pixels visible.
const advance_a = 12;
const advance_v = 8;
const advance_f = 6;
const advance_i = 4;
const advance_fi = 8;
const kern_av = -2;

const Fixture = struct {
    library: text.Library,
    face: text.Face,
    shaper: text.Shaper,

    fn init(options: text.FaceOptions) !Fixture {
        var library: text.Library = try .init();
        errdefer library.deinit();
        var face: text.Face = try .open(library, feature, options);
        errdefer face.deinit();
        const shaper: text.Shaper = try .init(16);
        return .{ .library = library, .face = face, .shaper = shaper };
    }

    fn deinit(self: *Fixture) void {
        self.shaper.deinit();
        self.face.deinit();
        self.library.deinit();
    }
};

// A ligature is the case where the glyph count is not the character count, and
// it is the reason `shape` reports a count rather than letting a caller derive
// one from the text.
//
// The cluster is the other half. Both characters merged into one glyph, so the
// glyph carries the cluster of the first of them: that is what a cursor is
// placed by, and a caller that assumed one glyph per character would put the
// cursor inside a glyph that has no inside.
test "a ligature is fewer glyphs than characters, under the first one's cluster" {
    var fixture: Fixture = try .init(.{ .pixel_size = pixel_size });
    defer fixture.deinit();

    var storage: [8]res.ShapedGlyph = undefined;
    const count = try fixture.shaper.shape(fixture.face, "fi", &storage);

    try testing.expectEqual(@as(usize, 1), count);
    try testing.expectEqual(@as(u32, 0), storage[0].cluster);
    // The ligature is narrower than the two glyphs it replaces, which is what a
    // ligature is for and what makes its effect a number rather than a
    // direction.
    try testing.expectEqual(@as(f32, advance_fi), text.advance(storage[0..count]));
    try testing.expect(advance_fi < advance_f + advance_i);
}

// The same two characters with something between them, which is the control:
// without it the test above would also pass on a face that lost a glyph.
test "the characters a ligature is made of still shape on their own" {
    var fixture: Fixture = try .init(.{ .pixel_size = pixel_size });
    defer fixture.deinit();

    var storage: [8]res.ShapedGlyph = undefined;
    const count = try fixture.shaper.shape(fixture.face, "f i", &storage);

    try testing.expectEqual(@as(usize, 3), count);
    try testing.expectEqual(@as(f32, advance_f), storage[0].x_advance);
    try testing.expectEqual(@as(f32, advance_i), storage[2].x_advance);
}

// Kerning moves the pen by an amount the face names, and it is applied to the
// glyph before the pair rather than to the one after it. A caller summing
// advances therefore gets the kerned width without knowing kerning exists,
// which is why `advance` is a sum and not a walk over pairs.
test "a kern pair moves the advance by the amount the face names" {
    var fixture: Fixture = try .init(.{ .pixel_size = pixel_size });
    defer fixture.deinit();

    var storage: [8]res.ShapedGlyph = undefined;
    const count = try fixture.shaper.shape(fixture.face, "AV", &storage);

    try testing.expectEqual(@as(usize, 2), count);
    try testing.expectEqual(@as(f32, advance_a + kern_av), storage[0].x_advance);
    try testing.expectEqual(@as(f32, advance_v), storage[1].x_advance);
    try testing.expectEqual(@as(f32, advance_a + advance_v + kern_av), text.advance(storage[0..count]));

    // The reverse pair is not kerned, so the same two glyphs the other way
    // round are the plain sum. Without this the test above would pass against a
    // face that had simply made every A narrower.
    const reversed = try fixture.shaper.shape(fixture.face, "VA", &storage);
    try testing.expectEqual(@as(f32, advance_a + advance_v), text.advance(storage[0..reversed]));
}

// The invariant the whole arrangement rests on: how a face is rasterised does
// not move what the shaper measured.
//
// It matters because a run is laid out from advances and drawn from coverage,
// and the two come from different code. If a hinting or antialiasing mode
// changed the advances, then a cache keyed by the face would be the least of
// it: the line would be laid out at one width and drawn at another.
//
// Ahem cannot test this. Every one of its advances is a whole em at every size,
// so it would survive a rounding to whole pixels unchanged and the test would
// pass without meaning anything. This face is proportional and its advances are
// not multiples of anything the grid would round to.
test "no rasterisation mode moves the advances the shaper reports" {
    const modes = [_]text.FaceOptions{
        .{ .pixel_size = pixel_size, .hinting = .none, .antialias = .grayscale },
        .{ .pixel_size = pixel_size, .hinting = .light, .antialias = .grayscale },
        .{ .pixel_size = pixel_size, .hinting = .none, .antialias = .subpixel },
        .{ .pixel_size = pixel_size, .hinting = .light, .antialias = .subpixel },
        .{ .pixel_size = pixel_size, .hinting = .light, .subpixel = .quarter },
    };

    var expected: [8]res.ShapedGlyph = undefined;
    var expected_count: usize = 0;
    for (modes, 0..) |options, index| {
        var fixture: Fixture = try .init(options);
        defer fixture.deinit();

        var storage: [8]res.ShapedGlyph = undefined;
        const count = try fixture.shaper.shape(fixture.face, "AVfi", &storage);
        if (index == 0) {
            expected = storage;
            expected_count = count;
            // The run this compares: a kern pair and a ligature, so four
            // characters come back as three glyphs.
            try testing.expectEqual(@as(usize, 3), count);
            continue;
        }
        try testing.expectEqual(expected_count, count);
        for (storage[0..count], expected[0..expected_count]) |got, want| {
            try testing.expectEqual(want.index, got.index);
            try testing.expectEqual(want.cluster, got.cluster);
            try testing.expectEqual(want.x_advance, got.x_advance);
            try testing.expectEqual(want.x_offset, got.x_offset);
        }
    }
}

// The face's own line metrics, which are exact here where Ahem's are not: the
// generator puts the ascent at thirteen pixels and the descent at three, both
// whole numbers of the 26.6 grid at this size, so these are compared with `==`
// rather than to within a step of it.
test "the generated face reports the line it was designed with" {
    var fixture: Fixture = try .init(.{ .pixel_size = pixel_size });
    defer fixture.deinit();

    const metrics = fixture.face.metrics();
    try testing.expectEqual(@as(f32, 13), metrics.ascent);
    try testing.expectEqual(@as(f32, -3), metrics.descent);
    try testing.expectEqual(@as(f32, 0), metrics.line_gap);
    try testing.expectEqual(@as(f32, pixel_size), metrics.lineHeight());
}
